# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Kartikeya Sharma
title: Data Science Generalist
email: kartikeyasharma733@gmail.com
website: 

# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username: 
github_username:  Kartikeya-95
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: 
linkedin_username: kartikeyasharma95
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: 
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
  # icon: fas fa-globe
  # url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I'm a Data Science Generalist having 6+ years of experience in descriptive, predictive & prescriptive analytics, doing modeling to solve business problems, drawing insights from data, supporting stakeholders in different aspects of business execution, solving various data & model releated queries. I've worked on diverse set of projects maintaining balance in business & technical acumnen. I've worked as an Individual Contributor in Data Engineering, Gen AI use cases, ML models, Mathematical Optimization, Adhoc Analysis etc. and also managed associates in projects ensuring smooth cross team functioning & timely delivery of modules & change requests. <br><br> 
  <mark>Functional Competencies:</mark> <b>Predictive Modeling</b>, <b>Forecasting</b>, <b>Mathematical Optimization</b>, <b>Statistics</b>, <b>Data Engineering</b>, <b>Data Visualization</b>, <b>Analytical Reasoning</b>, <b>Strong Business Communication</b> <br>
  <mark>Tools & Technologies:</mark> <b>Python</b>, <b>Excel</b>, <b>SQL</b>, <b>Power BI</b>, <b>Tableau</b>, <b>Alteryx Designer</b>, <b>Azure Databricks</b>, <b>Git Ecosystem</b>, <b>Cloud Fundamentals</b> <br>
  <mark>Domain Knowledge:</mark> <b>Airlines Revenue Management & Modeling</b>, <b>Retail Promotion & Markdown</b>, <b>Supply Chain Optimization</b>, <b>Pharma Analytics & Incentive Compensation</b>

content:
  - title: Recent Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Airlines Revenue Management & Modeling (Middle East Low Cost Carrier)
        #link: 
        # link_text: Project Website
        #additional_links:
         # - title:  sproogen/modern-resume-theme
          #  icon: fab fa-github
           # url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Most challenging ML implementation, operations & stakeholder management in critical operations business.
        description: | # this will include new lines to allow paragraphs
          I'm involved in this project during ML Operations & client handover phase and handled several data science modules namely Point to Point, Overbooking, Connecting Sectors, Movable Curtain & Load Factor Forecast modeling for a low cost carrier. I solved numerous client queries, helped them understand the functioning of models, incorporating change requests, monitoring, modifications, automations of models and creation of sector-wise performance monitoring mechanism based on RASK. 
  
      - layout: top-middle
        title: Retail Promotion & Markdown Modeling (American Retail Giant)
        #link: 
        # link_text: Project Website
        #additional_links:
         # - title:  sproogen/modern-resume-theme
          #  icon: fab fa-github
           # url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Project in pricing domain that revolved around retail promotion, markdown modeling and stakeholder management.
        description: | # this will include new lines to allow paragraphs
          I was involved in this project during on-going development phase and contributed to implementation and changes to regression discount modeling, redemption modeling, optimizing Baseline, Boost, Uplift model for forecasting sales units and prices at different levels of product hierarchy which resulted in 20% increase in QoQ sales & 5% increase in profit compared to past model performance.

      - layout: top-middle
        title: Supply Chain Optimization (French Food Manufacturing Giant)
        #link: 
        # link_text: Project Website
        #additional_links:
         # - title:  sproogen/modern-resume-theme
          #  icon: fab fa-github
           # url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Challenging Data Science Operations with complex Mathematical Optimization.
        description: | # this will include new lines to allow paragraphs
          I was involved in this project during operations phase ensuring seamless adoption of optimzation results by the stakeholder. I did enhancements in constraints related to capacity, stock volumes, demand, production and automated ingestion of files removing redudancies and streamlining the process as per requirements.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Boston Consulting Group
        link: https://www.bcg.com/x/
        # link_text: boringcompany.com
        sub_title: Senior Data Analyst
        caption: February 2023 - Present
        quote: >
          Solving complex business problems using AI/ML methodologies packaged as product
        description: | # this will include new lines to allow paragraphs
            - Refactored and enhanced multiple Data Science modules across domains of Airlines, Retail and Supply Chain to optimize revenue strategies, leading to improved pricing and performance.

            - Optimized load factor forecast model based on departure days buckets, RBD seats allocation distribution, flight sector level clustering resulting in 5% increase in revenue for top 10% domestic sectors.

            - Built load factor backtest pipeline enabling the assessment of new model performance on logged inference data by Days from Departure (DFD), ensuring continous model validation.

            - Integrated new user control parameters in different models, giving user more control towards the output which improved model recommendations adoption by 20%.

            - Created weighted regression model for discount and redemption modeling along with baseline calculation enhancements that resulted in 20% increase in sales & 5% increase in overall revenue.

            - Improved the prediction results for ~2000 new SKUs based on similarity matching using resembling SKUs with enough history & similar characteristics streamlining the launch strategies for new SKUs in the market.

            - Creation & enhancements of business constraints related to stock, capacity, demand & production to align the optimization output with business requirements. 

            - Resolved 50+ ad hoc client queries across multiple projects, ensuring timely model output explanations, data interpretation and business alignment.

            - Extensive collaboration with stakeholders and internal cross functional teams to solve business queries, designing and re-factoring of various machine learning and optimization models.

            - Created several Power BI and Tableau dashboards using different data sources (SQL databases, Flat Files, Sharepoint etc.) for model performance monitoring, adhoc analysis and KPIs reporting.

      - layout: left
        title: Axtria - Ingenious Insights
        link: https://www.axtria.com/
        # link_text: boringcompany.com
        sub_title: Senior Associate
        caption: December 2019 - February 2023
        quote: >
          Creating ML models and automating data pipelines for US based Pharmaceutical firms
        description: | # this will include new lines to allow paragraphs
            - Performed time series analysis to forecast monthly national sales for several therapeutic areas that helped in estimating revenue from sales and allocating goals to sales reps.

            - Performed clustering on number of prescriptions written by physicians to create segments that helped in targeting high potential physicians increasing overall sales by 10%.

            - Automated data processing & cleaning using python to generate different report extracts subsequently used in dashboards and analysis, saving 50% turnaround time in reports delivery.

            - Adhoc analysis on sales including comparisons, trending at different frequencies, correlation checks, IC plans’ performance, salesforce effectiveness across geographies, suggesting improvement actions and area of opportunities to stakeholders.

            - Onboarded new client on Axtria's in-house tool, gathering & documenting requirements in direct collaboration with stakeholders.

      - layout: left
        title: Accenture
        link: https://www.accenture.com/
        # link_text: boringcompany.com
        sub_title: Application Development Associate
        caption: February 2018 - June 2019
        quote: >
          REST and SOAP based web API development and data analysis.
        description: | # this will include new lines to allow paragraphs
            - Performed statistical analysis on logs generated in different request/response cycles to understand the trend of exceptions logged.

            - Automated fetching of exceptions and maintaining data from log files using python I/O and regular expressions.

            - Created Power BI dashboards to present different metrics related to the exceptions logged.

            - Created REST & SOAP based web APIs to integrate different backend systems.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Amity University
        caption: 2013 - 2017
        sub_title: B.Tech Computer Science & Engineering
        quote: >
          Completed the prescribed course in Computer Science and major projects with first division scoring 8.04 CGPA on a scale of 10.
        description: | # this will include new lines to allow paragraphs
          During my time at university I learnt most of my key skills that I have taken through my career such as teamwork, communication, working to tight deadlines and maintaining active lifestyle.

          I spent a lot of my free time in sports events and activities that helped me devlop team spirit and perseverance.

      - layout: left
        title: Great Lakes Institute of Management
        caption: Jul 2019 - Dec 2019
        sub_title: PGP in Data Science & Engineering
        quote: >
          Completed comphrensive full time classroom program in Data Science, specifically catered for practical and application based learning.
        description: | # this will include new lines to allow paragraphs
          During my time here, I learnt ML implementation, business communication and presentation skills that helped me excel in solving business problems using data utilizing various tools, methodologies and algorithms.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in Data Science some of my other interests and hobbies are:
      - Travelling
      - Sports (Badminton, Table Tennis, Football)
      - Bojutsu (Art of wielding a staff)
      - Arts, Culture & Spiritual Exploration 
    
# [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Look at this cool image  
# ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
